### ISSUE TITLE
SHT31 library with Arduino-ESP32 v2.0.5

### ISSUE THREAD

**Issue by oscarbaselga** [RobTillaart/SHT31#36]
Hi Rob,

I recently installed your library for my ESP32 T-Beam which I am building with the arduino-esp32 v1.0.6 ([from this url](https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json)). Everything works fine! 
However, I decided to update the arduino-esp32 version to 2.0.5 and same code does not work.
This is the conflicting code itself:
```
SensorX::SensorX() {
    Wire.begin();
    bool sht_begin = sht.begin(SHT31_ADDRESS);
    sht.reset();
    Wire.setClock(100000);
}
```
When commenting `sht` (declared as `SHT31 sht;`) calls, the rest of the code continues working.

I am using SHT31 v0.3.4 and TinyWireM v1.1.0.

Any help?

**Comment by RobTillaart** [comment]
Hi Oscar,

Thanks for the issue, I'm rather busy at the moment so it can take a few days before diving into this.

**Comment by RobTillaart** [comment]
Is there any error message?

**Comment by oscarbaselga** [comment]
Thanks for your quick response Rob!

No, there is no error message. The expected behavior is to print a debug message but it is not appearing. What is happening is that my ESP32 is interrupted by the watchdog:
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13160
load:0x40080400,len:3036
entry 0x400805e4
```

**Comment by RobTillaart** [comment]
> When commenting sht (declared as SHT31 sht;) calls, the rest of the code continues working.

This remark is ambiguous as sht is used multiple times.

Which line is commented?

Note: I have no hardware to setup an equivalent, so I depend on your testing.

**Comment by RobTillaart** [comment]
Can you create a minimal sketch that fails? As I have not enough clues yet.

I am using **packages\esp32\hardware\esp32\1.0.6** in my tests
